version: 2
updates:
  - directory: /client
    package-ecosystem: npm
    schedule:
      interval: daily
  - directory: /server
    package-ecosystem: gradle
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
