name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint

    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Format
              run: npm run format

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test
